Wireframe API Documentation

* General
** Will have to take into account reauthentication (periodic depending on token expiration and duration)
** Alternatives to replication
*** Can embed in iframe with limited functionality (would have to interact directly with 3rd party interface and not our own)


* Questions
** 'Saving' different items
*** where is this supposed to go? what file format? 

* Boards
** Social Feed Board
*** Facebook
**** Your app must not replicate core Facebook features or functionality, and must not promote your other apps that do so.
***** https://developers.facebook.com/policy
**** However, all the features are possible (showing posts, likes, comments)

*** Twitter
**** Rules against replicating core user experience:
***** You must obtain our permission to have more than 100,000 user tokens, and you may be subject to additional terms.
***** Use the Twitter API as provided by Twitter for functionalities in your Service that are substantially similar to a Twitter service feature and present this to your users as the default option.
***** Display a prominent link or button in your Service that directs new users to Twitter’s sign-up functionality.
**** Do not do the following:
***** Pay, or offer to pay, third parties for distribution. This includes offering compensation for downloads (other than transactional fees) or other mechanisms of traffic acquisition.
***** Arrange for your Service to be pre-installed on any device, promoted as a “zero-rated” service, or marketed as part of a specialized data plan.
***** Use Twitter Content or other data collected from users to create or maintain a separate status update or social network database or service.
**** i.e. possible to replicate, but not encouraged + limitations exist (must include link to Twitter signup)

*** Google+
**** Much more lax about replication policy
***** Don't circumvent any Google+ user interfaces that ensure the user is aware of and agrees to stream posts or the like made on his or her behalf.
***** Don’t circumvent any Google+ user interfaces or settings that limit the visibility of information, such as stream posts, from others.
***** https://developers.google.com/+/policies
**** i.e. make sure that appropriate interfaces are called in order to do posting/data access on the user's behalf

** Social Photo Board
*** Instagram
**** Terms of use:
***** Do not infringe on rights of Instagram users to their own media.
***** Cannot use Instagram name in application.
***** Cannot use Instagram API to crawl or store users' media without their express consent.
***** Cannot replicate the core user experience.
***** Do not overload the API with requests.
****** Limited to 5000 requests per hour per accession_token/client_id (applications that are viewed as spamming will be banned from the platform by spam detection systems).
**** Can replicate most of core functionality:
***** Get information about a user.
***** Get information about a user's relationship to you.
***** Access most popular photos/videos.
***** Get and create comments on a media object.
***** Get and set likes on a media object.

*** Flickr
**** Terms of use:
***** Comply with requirements/restrictions imposed on usage of the photos by their owners.
***** Cannot replicate the essential user experience.
***** Cannot display more than 30 Flickr user photos per page.
***** Cannot use unreasonable amount of bandwidth.
***** If application is commericial, Flickr reserves the right to monitor the application to ensure continued adherence to the terms and conditions.
***** Cannot use "flickr" or a pink "r" without a preceding "e" in the hostname of the application.
***** Must place the following notice prominently on your application: "This product uses the Flickr API but is not endorsed or certifed by Flickr."
***** Cannot use Flickr logo without explicit written permission from Flickr.
**** Can replicate most of core functionality:
***** View user comments/photos.
***** View blogs and upload photos.
***** Get user conteac lists and favorites.
***** View galleries and add photos.
***** Browse, join, leave and search groups.
***** Tag/untag photos.

*** Pinterest
**** Can create Pin it buttons.
**** Can display Pinterest boards.
***** https://www.concrete5.org/community/forums/customizing_c5/displaying-pinterest-boards/

** News Feed Board
*** Use Google News RSS feeds
*** Need better configuration options?
*** Bing News API (for development of news readers)
*** Feedzilla
*** Also can use specific newspaper API's & RSS
**** NY Times
**** ESPN
**** Most newspapers offer RSS feeds that can be used to supply data
*** Will have to decide whether we want to syndicate multiple news sources or use a third party news aggregator

** Cloud Storage Board
*** Dropbox
**** Showing files and opening them is okay
**** Basic Terms:
***** Don't build apps that promote IP or copyright infringement
***** Don't copy material from other sites unless you have the right to do so
***** Don't build file sharing apps
*** Google Drive
**** Same restrictions on content, but allow listing as above
*** 

*** Opening files
